### ISSUE TITLE
While building redirect $this->app returns null

### ISSUE THREAD

**Issue by DerSchwarzeJugo** [concrete5-community-store/community_store_payrexx#1]
Hi i've have been trying to get this extension to work. Unfortunately, when trying a checkout and while calling the redirect on line 64 in file /src/CommunityStore/Payment/Methods/CommunityStorePayrexx)/CommunityStorePayrexxPaymentMethod.php i get a en Error: "Call to a member function make() on null".
It seems like $this->app returns null in the AbstractController.

I am Using Concrete CMS Version 9.1.2 and PHP 7.4.32

Have you had similar problems in the past where this did not work?

Thank you for your time and kind regards

**Comment by Mesuva** [comment]
You could try updating these lines here:
https://github.com/concretecms-community-store/community_store_payrexx/commit/5ac68fc28883c346c5bbfedafcfa1975e8421ff8

I'm not set up to test this change, but I think the redirects are the issue here. 
Are you trying to set this up on V9?

This payment add-on is really quite old, and isn't something that has had much attention over the years.
I personally found Paxrexx to not be a great payment gateway, I'd recommend others like Stripe over this one.

**Comment by DerSchwarzeJugo** [comment]
Thank you Ryan, you saved my day :) It works like a charm with these adjustments now.

I see it has not been updated for a long time. I recommended Stripe to my client as well, but they wanted to go with payrexx.

Anyway, thank you for responding and providing a solution so quickly. This was some next level support.
